services:
  pdf-viewer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdf-book-viewer
    ports:
      - "5000:5000"
    volumes:
      - ./books:/app/books
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
      - PDF_DIR=/app/books
      - DATABASE_PATH=/app/data/books.db
      - APP_HOST=0.0.0.0
      - APP_PORT=5000
      - LOG_LEVEL=INFO
    restart: unless-stopped
